### PR TITLE
Make the actually used filter in WFS util configurable

### LINKED ISSUE #357: WFS Filters not working with a MapServer 7 backend
The OGC filters currently generated by BasiGX.util.WFS cause errors when requesting features from MapServer (with a GET request) such as:

`msWFSGetFeature(): WFS server error. Invalid or Unsupported FILTER in GetFeature : <Filter><BBOX><PropertyName>msGeometry</PropertyName><Envelope><gml:lowerCorner>-1399714.8619581475 6740828.650413123</gml:lowerCorner>      <gml:upperCorner>-289237.7150311069 7405525.048381017</gml:upperCorner></gml:Envelope></ogc:BBOX><gml:Envelope xmlns:gml=http://www.opengis.net/gml srsName=EPSG:3857><gml:lowerCorner>-1399714.8619581475 6740828.650413123</gml:lowerCorner><gml:upperCorner>-289237.7150311069 7405525.048381017</gml:upperCorner><Envelope></BBOX><Filter>
`

It appears these are caused by the following:

- any namespace properties in a tag e.g. xmlns:gml=http://www.opengis.net/gml
- an additional AND wrapper around the filter
- use of BBOX and Intersects?

An example of a working BBOX filter is:
`
<Filter><BBOX><PropertyName>msGeometry</PropertyName><Box%20srsName='EPSG:3857'><coordinates>-1009073.7780155,6855880.1040363 -754844.22198452,6990867.8959637</coordinates></Box></BBOX></Filter>
`

The above problems may be a MapServer issue rather than invalid filters.

### PR DESCRIPTION
**Pull request by marcjansen**
Currently we always creat an `And` combined `BBOX` and `Intersects` filter, which leads to problems depending on the backend.

This also updates Openlayers in the test and removes an outdated local copy of GeoExt in the tests.

Alternative to #358
Fixes #357 

Please review.

### CODE REVIEW

File: test/test-helper-functions.js [hunk 1]
```diff
@@ -171,5 +171,3 @@
...
...r)}},onBeforeGroupNodeCollapse:function(b){var a=this.self.KEY_COLLAPSE_REMOVE_OPT_OUT;b.cascadeBy(function(c){c[a]=true})},bindGroupLayerCollectionEvents:function(c){var a=this;if(c instanceof ol.layer.Group){var b=c.getLayers();b.on("remove",a.onLayerCollectionRemove,a);b.on("add",a.onLayerCollectionAdd,a);b.forEach(a.bindGroupLayerCollectionEvents,a)}},unbindGroupLayerCollectionEvents:function(c){var a=this;if(c instanceof ol.layer.Group){var b=c.getLayers();b.un("remove",a.onLayerCollectionRemove,a);b.un("add",a.onLayerCollectionAdd,a);b.forEach(a.unbindGroupLayerCollectionEvents,a)}},onLayerCollectionAdd:function(a){var b=this;if(b.collectionEventsSuspended){return}var c=a.element;b.addLayerNode(c);b.bindGroupLayerCollectionEvents(c)},onLayerCollectionRemove:function(a){var d=this;if(d.collectionEventsSuspended){return}var e=a.element;var c=d.getRootNode().findChildBy(function(f){return f.getOlLayer()===e},d,true);if(!c){return}if(e instanceof ol.layer.Group){d.unbindGroupLayerCollectionEvents(e)}var b=c.parentNode;b.removeChild(c)},suspendCollectionEvents:function(){this.collectionEventsSuspended=true},resumeCollectionEvents:function(){this.collectionEventsSuspended=false}});
```
Comment (hwbllmnn) [inline test/test-helper-functions.js]: Huh, I didn't know this wasn't needed any more for the tests, I guess it was probably never needed?

Comment (marcjansen) [reply test/test-helper-functions.js]: I think @weskamm has introduced it back in the days, but the tests run fine without this line. Thanks god.

**Comment by marcjansen** [comment]
Thanks for the review.
